owner: yashafake
repo: upptime-status

sites:
  - name: Vsedomatut.ru
    url: https://vsedomatut.ru/
    slug: vsedomatut-ru
  - name: Вседоматут.рф
    url: https://xn--80adgd0blsnaj.xn--p1ai/
    slug: vsedomatut-rf
  - name: Etern8
    url: https://etern8.tech/
  - name: DH22
    url: https://dh22.ru/

status-website:
  baseUrl: /upptime-status
  name: Black8 Status
  introTitle: Black8 Uptime Status
  introMessage: Automated uptime and incident monitoring for production websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
