owner: yashafake
repo: upptime-status

sites:
  - name: Dommarket
    url: https://dommarket.black8.tech/
  - name: Etern8
    url: https://etern8.tech/
  - name: DH22
    url: https://dh22.ru/

status-website:
  baseUrl: /upptime-status
  name: Black8 Status
  introTitle: Black8 Uptime Status
  introMessage: Automated uptime and incident monitoring for production websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
